apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{APP_NAME}}
  name: {{APP_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      containers:
        - image: {{IMAGE_NAME}}
          imagePullPolicy: IfNotPresent
          name: {{APP_NAME}}
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 120
          readinessProbe:
            httpGet:
              port: 8080
              path: /health
              scheme: HTTP
#      imagePullSecrets:
#        - name: mc-repositry